app:
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  interval: 10000000
  access-type: orm
  limit: 100
  message-transport: http

timeout: 10

api:
  github:
    repos-events: https://api.github.com/repos/{owner}/{repos}/events
  stackoverflow:
    timeline: https://api.stackexchange.com/2.3/questions/{question}/timeline?site=stackoverflow&order=desc&key={key}
    posts: https://api.stackexchange.com/2.3/posts/{post}?site=stackoverflow&filter=withbody&key={key}
  bot:
    update: http://localhost:8080/api/v1/updates

db:
  url: jdbc:postgresql://localhost:5432/link_tracker_bot
  username: ${DB_USER} # env variable
  password: ${DB_PASSWORD} # env variable

resilience4j:
  retry:
    instances:
      scrapper:
        maxAttempts: 3
        waitDuration: 500
        exponential-backoff-multiplier: 1.5
        enable-exponential-backoff: true
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
  ratelimiter:
    instances:
      scrapper:
        limitForPeriod: 3
        timeoutDuration: 0s
        limitRefreshPeriod: 5s
  circuitbreaker:
    instances:
      bot:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumRequiredCalls: 20
        failureRateThreshold: 50
        permittedCallsInHalfOpenState: 2
        waitDurationInOpenState: 5s

kafka:
  topic:
    chats: chats
    links: links
    list-links: list-links
    events: events

spring:
  application:
    name: Scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/link_tracker_bot
    username: ${DB_USER} # env variable
    password: ${DB_PASSWORD} # env variable
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: scrapper-consumer-group

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
